apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/gbenhaim/devfile-sample-python-basic?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: devfile-sample-python-basic-main
    appstudio.openshift.io/component: python-app
    pipelines.appstudio.openshift.io/type: build
  name: python-app-on-push
  namespace: gbenhaim-tenant
spec:
  params:
  - name: dockerfile
    value: docker/Dockerfile
  - name: git-url
    value: '{{repo_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/gbenhaim-tenant/devfile-sample-python-basic-main/python-app:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineSpec:
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.set-results.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.set-results.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.set-results.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.set-results.results.commit)
    tasks:
    - name: set-results
      taskSpec:
        results:
          - name: IMAGE_URL
            description: ""
          - name: IMAGE_DIGEST
            description: ""
          - name: url
            description: ""
          - name: commit
            description: ""
        steps:
          - name: echo
            image: ubuntu
            script: |
              #!/usr/bin/env bash
              echo -n "quay.io/redhat-user-workloads/gbenhaim-tenant/backplane-must-gather/backplane-must-gather-cr7q:482dbdea3bede804a1233f048e0e40c1c43bc38e" > $(results.IMAGE_URL.path)
              echo -n "sha256:dbca4eb18f0786b3be506830c9a2e79d850053e792b0cd9f072a530e3f756bb9" > $(results.IMAGE_DIGEST.path)
              echo -n "https://github.com/gbenhaim/backplane-must-gather" > $(results.url.path)
              echo -n "482dbdea3bede804a1233f048e0e40c1c43bc38e" > $(results.commit.path)
    workspaces:
    - name: workspace
    - name: git-auth
      optional: true
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
